# spring-cloud-gcp-dlp

==Google Cloud Platform DLP on Spring Framework

This project makes it easy for Spring users to integrate Google Cloud Platform 
Data Loss Prenvetion(DLP) API into their applications. 
You can find the spring cloud gcp project website https://spring.io/projects/spring-cloud-gcp[here].

Currently, this repository provides support for:

* link:spring-cloud-gcp-dlp[Google Cloud DLP API Templete]
* Spring Boot starters
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter-vision[Google Cloud DLP API]

If you have any other ideas, suggestions or bug reports, please use our https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues[GitHub issue tracker] and let us know!
Also, please take the https://www.techvalidate.com/registration/google-spring-cloud-gcp-customer-survey[*Spring Cloud GCP 5 Minute Customer Survey*] to help us learn about your usage of the project.
We would love to hear from you!

If you want to collaborate in the project, we would also love to get your Pull Requests.
Before you start working on one, please take a look at our link:CONTRIBUTING.md[collaboration manual].

== Spring Cloud GCP Bill of Materials (BOM)

If you're a Maven user, add our BOM to your pom.xml `<dependencyManagement>` section.
This will allow you to not specify versions for any of the Maven dependencies and instead delegate versioning to the BOM.

[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>spring-cloud-gcp-dependencies</artifactId>
            <version>2.0.4</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

== Snapshots Repository

We offer `SNAPSHOT` versions of the project that always reflect the latest code changes to the underlying GitHub repository for Spring Cloud GCP via the Sonatype Snapshots Repository:

[source,xml]
----
<repositories>
    <repository>
        <id>snapshots-repo</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
----

For example, the version `2.0.5-SNAPSHOT` is available from this repository.

== Spring Boot Starters

Spring Boot greatly simplifies the Spring Cloud GCP experience.
The starters handle the object instantiation and configuration logic so you don't have to.

Every starter depends on the GCP starter to provide critical bits of configuration, like the GCP project ID or OAuth2 credentials location.
You can configure these as properties in, for example, a properties file:

[source]
----
spring.cloud.gcp.project-id=[YOUR_GCP_PROJECT_ID]
spring.cloud.gcp.credentials.location=file:[LOCAL_PRIVATE_KEY_FILE]
spring.cloud.gcp.credentials.scopes=[SCOPE_1],[SCOPE_2],[SCOPE_3]
----

These properties are optional and, if not specified, Spring Boot will attempt to automatically find them for you.
For details on how Spring Boot finds these properties, refer to the https://cloud.spring.io/spring-cloud-gcp[documentation].

NOTE: If your app is running on Google App Engine or Google Compute Engine, in most cases, you should omit the `spring.cloud.gcp.credentials.location` property and, instead, let the Spring Cloud GCP Core Starter find the correct credentials for those environments.
